services:
  - type: web
    name: kurisu-wechat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TOKEN
        value: kurisu_token_2024
